name: xui-checker

services:
  xui-checker:
    build: .
    image: xui-checker
    container_name: xui-checker
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
    restart: unless-stopped
    ports:
      - "8001:8001"
    env_file:
      - .env
